apiVersion: apps/v1
kind: Deployment
metadata:
  name: kishq-app
  labels:
    app: kishq-app
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  selector:
    matchLabels:
      app: kishq-app
  template:
    metadata:
      labels:
        app: kishq-app
    spec:
      containers:
      - name: kishq-app
        image: iamsaikishore/image-name:latest        
        ports:
        - containerPort: 8080        
        readinessProbe:
          httpGet:
            path: /webapp
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 30
      terminationGracePeriodSeconds: 30            
---
apiVersion: v1
kind: Service
metadata:
  name: kishq-app-service
  labels:
    app: kishq-app
spec:
  type: NodePort
  selector:
    app: kishq-app
  ports:
  - name: http
    port: 80
    targetPort: 8080
    nodePort: 30000
  - name: https
    port: 443
    targetPort: 8081
    nodePort: 31200

